name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! |
        We will try our best to get it resolved urgently!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What exactly happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version Details
      description: What version of our software are you running?
      placeholder: ex. v0.1.0.4
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What OS are you using?
      multiple: true
      options:
        - Microsoft Windows
        - MacOS
        - Linux
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Log Information
      description: Please copy and paste any relevant log output.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Calixte-Williams/set08803_gw/tree/feature/CodeofConduct).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
