@startuml

actor User as "Employee"

rectangle DB as "World Database"

rectangle "World Country Report" {
    usecase UC1 as "Get Countries by Population"

    usecase UCa as "PRINT Countries"

    User - UC1
    UC1 ..> UCa : include
    UC1 - DB
}
@enduml